title: Django Config Templates
description: This site contains a bunch of config files for the Django Project created and bundled by ryuuzu.
theme: just-the-docs
email: me@ryuuzu.xyz
twitter_username: UtsavGurmachhan
github_username: ryuuzu

url: https://github.ryuuzu.xyz/django-configs

# aux_links:
#     Template Repository: https://github.com/just-the-docs/just-the-docs-template
